### ISSUE TITLE
Set Local Storage to the To_Do_List

### ISSUE THREAD

**Issue by narasimha-1511** [narasimha-1511/ToDOList#1]
Current Behaviour: data is getting erased after realoading

Expected Behaviour:  data must be present after reloading the page

**Comment by anevski-stefan** [comment]
@narasimha-1511 I want to work on this issue, can you assign me?

**Comment by narasimha-1511** [comment]
go an @anevski-stefan :confetti_ball:

**Comment by anevski-stefan** [comment]
@narasimha-1511 it's done, can you review it?
